### ISSUE TITLE
PVC on Pending state 

### ISSUE THREAD

**Issue by ilyesAj** [mrbobbytables/k8s-intro-tutorials#5]
in storage lab: [lab](https://github.com/mrbobbytables/k8s-intro-tutorials/blob/master/storage/README.md#exercise-understanding-persistent-volumes-and-claims)

if you create a PVC without consuming it you will have the PVC on `pending` state with `WaitForFirstConsumer` message .

to generate the desired error  `FailedBinding` i suggest you add a consumer on yaml file :
````yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-selector-example
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: hostpath
---
apiVersion: v1
kind: Pod
metadata:
  name: consumer
spec:
  containers:
    - name: consumer
      image: alpine:latest
      volumeMounts:
        - mountPath: /html
          name: html
      command: ["/bin/sh","-c"]
      args:
        - while true ; do
            echo "i m here at $(date)" >> /html/logs ;
            sleep 10;
          done
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: pvc-selector-example
```` 

kubernetes version:  v1.17.2
