### ISSUE TITLE
Windows host persistent volume problem

### ISSUE THREAD

**Issue by agnoam** [mrbobbytables/k8s-intro-tutorials#6]
Hey,
I'm trying to make a deployment with a local persistent volume attached to it. (for development)

I managed to do this on Linux like `Kubernetes declarations` below.
I tried the `C:\` format in `hostPath.path` but, it seems Kubernetes not support this.

Does anyone know how to make this work on Windows ?

<details>
  <summary>Kubernetes declarations</summary>

# Volume declaration
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/k8s/myTestVolume"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

# Deployment declaration
```yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      volumes:
        - name: test-storage
          persistentVolumeClaim:
            claimName: test-volume-claim
      securityContext: {}
      containers:
        - name: test-container
          image: busybox
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /home/data
              name:  test-storage
```
</details>
